[package]
name = "VariDLAv2"
version = "0.1.0"
edition = "2021"

[dependencies]
blue_engine = "0.5.14"
gl = "0.14.0"
image = "0.25.2"
obj-rs = "0.7.1"
petgraph = "0.6.5"
rfd = "0.14.1"
sdl2 = "0.37.0"
vulkano = { version = "0.34.1", features = ["macros"] }
winit = "0.30.3"
